name: CD - Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["CI - Build & Push Docker"]
    types: [ "completed" ]

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set KUBECONFIG
        shell: powershell
        run: |
          Write-Host "Setando KUBECONFIG para Minikube no Windows"
          $env:KUBECONFIG = "$env:USERPROFILE\.kube\config"
          kubectl config current-context
          kubectl get nodes

      - name: Set image vars
        id: vars
        shell: powershell
        run: |
          $SHORT_SHA = $env:GITHUB_SHA.Substring(0,7)
          Write-Output "IMAGE=vinimf14/monitor" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          Write-Output "TAG_SHA=$SHORT_SHA" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Deploy to Kubernetes
        shell: powershell
        run: |
          Write-Host "Atualizando deployment monitor com a nova imagem"
          kubectl set image deployment/monitor monitor=${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG_SHA }} -n default
          kubectl rollout status deployment/monitor -n default
